import CategoryPage from "../../components/category-page/category-page";

const PolicyPage = () => {

    return(
        <>
         <h2>Policy</h2>
         <article>
            <h3></h3>
            <p>
                Chupa chups cheesecake candy canes tart gummi bears sweet roll bear claw dragée. Cheesecake donut gingerbread cupcake biscuit jelly beans. Pudding tart bonbon croissant marzipan danish icing donut. Jelly beans chupa chups fruitcake pudding donut ice cream liquorice. Croissant donut biscuit jelly-o caramels fruitcake lollipop. Toffee pastry carrot cake dragée lemon drops. Cookie bonbon brownie gummi bears candy. Tart dragée soufflé sesame snaps brownie wafer bear claw pudding. Sugar plum sugar plum chocolate cake jelly beans bonbon muffin. Chocolate bar halvah shortbread jelly candy apple pie jujubes tiramisu danish. Macaroon topping wafer marzipan cake wafer fruitcake. Carrot cake sesame snaps sugar plum carrot cake tart sweet powder.
                Pudding brownie marzipan sweet muffin icing liquorice bonbon. Brownie danish jelly-o chocolate bar gummi bears biscuit pie candy. Liquorice gummies dragée caramels chocolate bar jelly beans lemon drops fruitcake. Cookie gummi bears cake tiramisu jelly. Sweet chupa chups chocolate bar cheesecake chocolate cake. Pie donut toffee danish tiramisu oat cake fruitcake. Chocolate oat cake macaroon cookie dragée. Muffin tart cookie carrot cake brownie brownie bonbon bonbon. Caramels cookie dragée carrot cake dragée. Shortbread sugar plum tootsie roll gummies cupcake wafer. Lollipop candy jelly-o gummi bears cake croissant donut brownie. Chupa chups shortbread shortbread bonbon muffin gummi bears. Lollipop pie toffee gingerbread jelly croissant jelly beans cake. Dessert chocolate bar jelly shortbread carrot cake.
                Gummies topping pudding cheesecake gingerbread pastry tart dessert dessert. Gummi bears jujubes jelly-o sugar plum gummies cotton candy oat cake. Gummies jelly beans biscuit cupcake dessert chupa chups. Dessert jelly beans pie danish cupcake bonbon. Dragée pie macaroon tart chocolate bar pastry chupa chups. Icing donut apple pie dessert lemon drops. Dragée halvah lollipop tootsie roll pudding muffin muffin. Toffee chocolate bar topping jelly beans chocolate bar jelly-o. Toffee marshmallow jelly apple pie sesame snaps cupcake jujubes halvah chupa chups. Muffin macaroon tootsie roll sugar plum caramels. Lemon drops marzipan chupa chups bear claw fruitcake dragée. Oat cake chocolate toffee candy canes marzipan. Croissant tootsie roll icing liquorice dessert gingerbread jelly-o.
                Jelly pastry chocolate bar pastry carrot cake chocolate bar croissant. Cake caramels lollipop ice cream carrot cake. Ice cream bear claw pastry ice cream jujubes. Biscuit tootsie roll powder caramels gummies chupa chups. Powder sesame snaps icing fruitcake sweet roll gummies jujubes dessert. Bonbon toffee tart cookie tootsie roll cotton candy. Caramels jelly beans pudding candy dragée biscuit apple pie. Chocolate pudding jelly beans shortbread bonbon jelly beans cookie cotton candy marshmallow. Soufflé cotton candy tart cupcake tiramisu tiramisu gummi bears. Lemon drops tart sweet roll muffin icing lollipop halvah bonbon. Biscuit powder candy canes donut chocolate cake jujubes. Fruitcake jelly beans soufflé candy canes tiramisu. Jelly-o icing tiramisu fruitcake bear claw. Powder brownie bonbon lollipop jelly beans pudding.
                Cupcake fruitcake danish carrot cake croissant jujubes macaroon cotton candy. Chocolate cake sesame snaps brownie carrot cake ice cream marshmallow oat cake caramels. Pudding cake gingerbread cotton candy carrot cake. Tiramisu gingerbread sweet cookie sweet gummies cake gingerbread marzipan. Danish jelly beans tart chocolate bar cheesecake tootsie roll cotton candy topping. Oat cake candy canes liquorice cake apple pie topping sugar plum. Chocolate shortbread muffin donut candy biscuit gingerbread. Sweet carrot cake sesame snaps candy chocolate bar lemon drops. Liquorice chocolate cake croissant toffee jelly-o macaroon. Lemon drops marshmallow cotton candy marshmallow pie. Toffee dragée croissant cake dessert sugar plum cake cookie. Apple pie croissant tart tootsie roll macaroon liquorice marzipan tart pudding. Shortbread donut gummi bears pastry gummi bears tootsie roll cake icing. Ice cream bonbon pie sugar plum fruitcake toffee icing.
                Gingerbread pastry pastry carrot cake gummies lollipop. Bear claw lollipop apple pie candy bonbon gingerbread sweet roll brownie. Chocolate bar chocolate liquorice lemon drops oat cake sweet roll dragée sweet shortbread. Cupcake icing wafer tart cheesecake croissant cookie. Cookie jujubes topping fruitcake tiramisu gummi bears jujubes. Marshmallow apple pie bear claw cotton candy brownie muffin chocolate bar. Jujubes halvah chocolate toffee chocolate brownie pudding. Caramels croissant cupcake tart lollipop caramels toffee carrot cake. Sweet roll powder topping gingerbread topping jujubes chupa chups icing fruitcake. Tiramisu sweet roll lemon drops bonbon icing sugar plum. Cake cupcake pie macaroon lemon drops danish caramels carrot cake brownie. Dessert croissant lollipop donut cake jelly. Chocolate cake chocolate cake jujubes biscuit jelly sesame snaps chocolate bar gummies.
                Chupa chups apple pie muffin soufflé candy canes tootsie roll cheesecake pudding. Macaroon cheesecake chocolate bar chocolate cake oat cake fruitcake cookie biscuit. Macaroon sesame snaps sugar plum cotton candy lemon drops pudding. Apple pie chocolate pudding marshmallow jelly beans dessert ice cream. Gingerbread powder biscuit carrot cake toffee. Lollipop jujubes dessert soufflé croissant jelly beans candy. Powder marzipan chocolate bar pie pastry danish macaroon bonbon. Lollipop chocolate bar topping cookie sugar plum cookie pastry jelly pastry. Bonbon gummies sweet cupcake cotton candy biscuit bear claw. Chocolate cake fruitcake chocolate sweet roll cheesecake. Pastry marshmallow sugar plum cupcake bonbon macaroon wafer cookie. Sweet jelly beans topping marzipan cake jujubes marzipan brownie biscuit. Topping cookie brownie tootsie roll donut shortbread tart tootsie roll chocolate.
                Jelly chocolate cake wafer soufflé apple pie. Bonbon muffin caramels jelly beans pastry. Bonbon bear claw toffee muffin cupcake oat cake macaroon topping ice cream. Pastry bear claw dragée oat cake caramels cupcake halvah donut. Cake tart bonbon bonbon tiramisu shortbread cotton candy. Dragée chocolate bar gummies shortbread caramels icing pudding marzipan. Jelly beans marshmallow jelly-o cheesecake pastry wafer cotton candy. Jelly-o shortbread dessert brownie brownie icing lollipop chocolate bar. Toffee tart soufflé pudding gummi bears. Muffin jelly caramels fruitcake tart gummies marshmallow. Jujubes candy canes sweet roll apple pie chocolate bar. Jujubes biscuit cheesecake ice cream chocolate cake lollipop danish tiramisu. Biscuit dessert chocolate cake caramels powder. Candy canes tart sugar plum sugar plum sugar plum.
                Topping danish cake candy croissant chocolate soufflé. Chocolate bar jelly-o candy canes jujubes oat cake chupa chups biscuit. Jelly-o chocolate bar chocolate bar tiramisu carrot cake bonbon halvah. Candy canes chocolate bar dragée apple pie dessert sweet roll. Oat cake lemon drops sweet roll cake bear claw bonbon sweet chocolate cake. Sweet jelly-o candy canes topping chocolate cake cake. Jelly beans chupa chups danish macaroon wafer biscuit. Biscuit cake brownie powder gingerbread wafer. Lemon drops danish candy canes bonbon tiramisu chocolate bar. Carrot cake chocolate cake lollipop fruitcake gingerbread gummies soufflé bonbon cupcake. Chocolate sweet roll tiramisu tootsie roll chupa chups cotton candy. Cake pie dessert cheesecake apple pie toffee. Liquorice dragée tiramisu shortbread sugar plum sweet tart. Topping tiramisu fruitcake marshmallow cake chupa chups liquorice.
                Pie sesame snaps apple pie chupa chups cheesecake tiramisu. Oat cake sugar plum cake candy canes brownie. Liquorice pastry cake jelly carrot cake toffee. Gummi bears marzipan cake lemon drops sesame snaps chupa chups. Sesame snaps bear claw cotton candy gummi bears halvah sweet roll shortbread. Apple pie pastry cookie lemon drops macaroon cheesecake chocolate. Wafer jelly muffin brownie marzipan. Muffin chocolate cake dragée lollipop tootsie roll fruitcake. Cookie candy fruitcake tiramisu candy canes cheesecake. Ice cream cookie chocolate bar topping soufflé. Pie chupa chups croissant tootsie roll lemon drops jelly lollipop lollipop tart. Shortbread pie sweet roll powder fruitcake. Powder soufflé jelly wafer candy fruitcake gummies marshmallow sugar plum.{/*  */}
            </p>
         </article>
        </>
    )
}

export default PolicyPage;